const GET_MOVIE_DETAIL_LOADING = 'GET_MOVIE_DETAIL_LOADING';
const GET_MOVIE_DETAIL_SUCCESS = 'GET_MOVIE_DETAIL_SUCCESS';
const GET_MOVIE_DETAIL_FAILURE = 'GET_MOVIE_DETAIL_FAILURE';

export {
  GET_MOVIE_DETAIL_LOADING,
  GET_MOVIE_DETAIL_SUCCESS,
  GET_MOVIE_DETAIL_FAILURE
};
