const FETCHING_MOVIES = 'FETCHING_MOVIES';
const FETCHING_MOVIES_SUCCESS = 'FETCHING_MOVIES_SUCCESS';
const FETCHING_MOVIES_FAILURE = 'FETCHING_MOVIES_FAILURE';
const CLEAR_RESULTS = 'CLEAR_RESULTS';
const SET_SELECTED_MOVIE = 'SET_SELECTED_MOVIE';

export {
  FETCHING_MOVIES,
  FETCHING_MOVIES_SUCCESS,
  FETCHING_MOVIES_FAILURE,
  CLEAR_RESULTS,
  SET_SELECTED_MOVIE
};
