const FETCHING_MOVIES = 'FETCHING_MOVIES';
const FETCHING_MOVIES_SUCCESS = 'FETCHING_MOVIES_SUCCESS';
const FETCHING_MOVIES_FAILURE = 'FETCHING_MOVIES_FAILURE';

export { FETCHING_MOVIES, FETCHING_MOVIES_SUCCESS, FETCHING_MOVIES_FAILURE };
